import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";

//const inter = Inter({ subsets: ["latin"], weight: ["400","500"] });
//const dmSans = DM_Sans({ subsets: ["latin"], weight: ["500","700"] });

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],      // Regular & Medium
  variable: "--font-inter"
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["500", "700"],      // Medium & Bold
  variable: "--font-dmsans"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${dmSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
