name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CADENCE_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.CADENCE_EC2_SSH_KEY }}
          source: "./apps/backend"
          target: "~/cadence/apps/backend"

      - name: Restart Cadence on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CADENCE_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.CADENCE_EC2_SSH_KEY }}
          script: |
            cd ~/cadence/apps/backend

            # Cleanup step
            docker stop cadence-backend || true
            docker rm cadence-backend || true
            docker container prune -f
            docker image prune -f
            docker builder prune -f
            
            # Build and run the backend
            docker build -t cadence-backend .
            docker run -d --restart always -p 3000:3000 -e DEMO_MODE=true --name cadence-backend cadence-backend

