name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BEATSYNC_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.BEATSYNC_EC2_SSH_KEY }}
          source: "."
          target: "~/beatsync"

      - name: Restart BeatSync on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BEATSYNC_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.BEATSYNC_EC2_SSH_KEY }}
          script: |
            cd ~/beatsync
            npm install
            pm2 restart all
