name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CADENCE_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.CADENCE_EC2_SSH_KEY }}
          source: "."
          target: "~/cadence"

      - name: Restart Cadence on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CADENCE_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.CADENCE_EC2_SSH_KEY }}
          script: |
            cd ~/cadence

            # Cleanup step
            docker container prune -f
            docker image prune -a -f
            docker builder prune -a -f

            docker stop cadence || true
            docker rm cadence || true
            docker build -t cadence-backend .
            docker run -d --restart always -p 3000:3000 -e DEMO_MODE=true --name cadence cadence-backend

